Algoritmo "Número positivo"
// Disciplina   : [Lógica de Programação em JS]
// Professor   : Jailson
// Descrição   : Verifique se o número é positivo ou negativo
// Autor(a)    : Stefany Barreto
// Data atual  : 10/04/2024
Var
   n: inteiro

Inicio
   Escreva("Escreva um número: ")
   Leia(n)
   Se (n >= 0) entao
      Escreva("É positivo")
   Senao
      Escreva("É negativo")
   Fimse


Fimalgoritmo