Algoritmo "Área do Quadrado"
// Disciplina   : [Lógica de Programação com JS]
// Professor   : Jailson
// Descrição   : Area e Perimetro de um Quadrado
// Autor(a)    : Stefany Barreto Rocha
// Data atual  : 18/04/2024
Var
// Seção de Declarações das variáveis
lado:real

Inicio

Escreval("Area do Quadrado")
Escreva("Digite o valor de um Lado: ")
Leia(lado)
Escreval("A Área é: ", lado * lado)

Fimalgoritmo