Algoritmo "Valor de Veiculo"
// Disciplina   : [Lógica de Programação com JS]
// Professor   : Jailson
// Descrição   : Comprar um carro
// Autor(a)    : S t e f a n y B a r r e t o
// Data atual  : 08/04/2024
Var
custo, calc:real

Inicio
Escreva("Digite o valor de fabrica do veículo: ")
Leia(custo)

calc <- custo * (28/100) + custo * (45/100) + custo

Escreva("O valor final (impostos + valor do distribuidor) é: ", calc )

Fimalgoritmo