Algoritmo "Troca De Valores"
// Disciplina   : [Lógica de Programação com JS]
// Professor   : Jailson
// Descrição   : Troca o valor de duas variaveis
// Autor(a)    : Stefany Barreto Rocha
// Data atual  : 18/04/2024
Var
n1, n2, aux:inteiro

Inicio
Escreva("Digite o primeiro valor: ")
Leia(n1)
Escreva("Digite o segundo valor: ")
Leia(n2)
aux <- n1
n1 <- n2
n2 <- aux

Escreva("Os valores trocados são, respectivamente: ", n1, n2)

Fimalgoritmo