Algoritmo "Área do Circulo"
// Disciplina   : [Lógica de Programação com JS]
// Professor   : Jailson
// Descrição   : Area e Perimetro de um Circulo
// Autor(a)    : Stefany Barreto Rocha
// Data atual  : 18/04/2024
Var
// Seção de Declarações das variáveis
raio:real

Inicio

Escreval("Area do Circulo")
Escreva("Digite o valor do Raio: ")
Leia(raio)
Escreval("A Área é: ", pi * (raio * raio))

Fimalgoritmo