Algoritmo "Modulo de um número"
// Disciplina   : [Linguagem e Lógica de Programação com JS]
// Professor   : Jailson
// Descrição   : Modulo de um número
// Autor(a)    : Stefany Barreto
// Data atual  : 05/04/2024
Var
   n:inteiro

Inicio
   Escreva("Digite um valor: ")
   Leia(n)

   Se n < 0 entao
      Escreva("O módulo de",n," é: ", n * -1)
   Senao
      Escreva("O módulo de",n," é: ", n)
   FimSe



Fimalgoritmo