Algoritmo "Valor par ou impar"
// Disciplina  : [Linguagem e Lógica de Programação em JS]
// Professor   : Jailson
// Descrição   : Valor par ou impar
// Autor(a)    : Stefany Barreto
// Data atual  : 07/04/2024
Var
   n:inteiro

Inicio
   Escreva("Digite um valor: ")
   Leia(n)

   Se n % 2 = 0 entao
      Escreva("O valor é par")
   Senao
      Escreva("O valor é impar")
   FimSe

Fimalgoritmo