Algoritmo "Dentro ou fora do intervalo"
// Disciplina  : [Linguagem e Lógica de Programação em JS]
// Professor   : Jailson
// Descrição   : Dentro ou fora do intervalo
// Autor(a)    : Stefany Barreto
// Data atual  : 07/04/2024
Var
   n:inteiro

Inicio
   Escreva("Digite um valor (de 1 a 9): ")
   Leia(n)

   se (n < 1) ou (n > 9) entao
      Escreva("Número fora do intervalo permitido")
   senao
      Escreva("Número dentro do intervalo permitido")
   fimSe

Fimalgoritmo