Algoritmo "Número menor que 3"
// Disciplina  : [Linguagem e Lógica de Programação em JS]
// Professor   : Jailson
// Descrição   : Número menor que 3
// Autor(a)    : Stefany Barreto
// Data atual  : 07/04/2024
Var
   n:inteiro

Inicio
   Escreva("Digite um valor (menor que 3): ")
   Leia(n)

   Se n > 3 entao
      Escreva("Número maior que 3!")
   Senao
      Escreva("Número é: ", n)
   FimSe

Fimalgoritmo