Algoritmo "Celsius para Fahrenheit"
// Disciplina   : [Lógica de Programação em JS]
// Professor   : Jailson
// Descrição   : Celsius para Fahrenheit
// Autor(a)    : Stefany Barreto
// Data atual  : 28/03/2024
Var
grausC, conversao: real

Inicio
Escreva("Digite a temperatura em Celsius: ")
Leia(grausC)

conversao <- (9 * grausC + 160) / 5
Escreva("Em Fahrenheit fica: ", conversao)

Fimalgoritmo