Algoritmo "Impares de 0 a 20"
// Disciplina  : [Linguagem e Lógica de Programação com JS]
// Professor   : Jailson
// Descrição   : Impares de 0 a 20
// Autor(a)    : Stefany Barreto
// Data atual  : 15/04/2024
Var
   count:inteiro

Inicio
   para count de 0 ate 20 passo 1 faca
      Se count % 2 = 1 entao
         Escreval("O número", count, " é Impar.")
      FimSe
   FimPara

Fimalgoritmo